### ISSUE TITLE
Cannot pipe to constructor

### ISSUE THREAD

**Issue by bbrk24** [DanielXMoore/Civet#1003]
```civet
x |> new Foo
```
becomes
```js
new Foo()(x)
```
I don't think this makes sense. The only classes that are callable are `Function` and `Proxy`, and neither of them are constructed with no arguments to the ctor. You also can't subclass `Proxy` (not sure about `Function`).

Additionally, `x |> new Foo &` can't be used as a workaround, as that gives a ParseError.

If, for whatever reason, this behavior is desired, this could be written
```civet
x |> new Foo()
```
In many other positions, `new Foo` and `new Foo()` are equivalent.

**Comment by angelhdzmultimedia** [comment]
Hello, not an expert on TS or Civet, but this thread caught my attention.

Creating an object/instance of a class (either with ESM classes or a Function) with the new operator, is not the same as calling a function. It's special syntax.

```ts
function MyClass(value: string) {

}

const x: string = 'abc'
// new MyClass(x) not equal to MyClass(x)
// and new MyClass(x)  not equal to MyClass.call()
// and new MyClass(x)  not equal to MyClass.prototype.constructor()
```

Pipes only chains functions to be called.

Also, using new operator returns an object, not a function to be called, so the pipe operator can't call it. And we can't create an object/instance of a class without the new operator, just by calling the MyClass.prototype.constructor.

This is proven by calling a class without the new operator and the error thrown: `TypeError: Class constructor MyClass cannot be invoked without 'new'`. If what made an instance of a class was just calling the class constructor method, then the new keyword wouldn't be neccessary and wouldn't exist (of course each language has its own way of creating instances of classes, Python doesn't uses any keyword, just call the class as a function, and in Rust, we use the name of the class and curly brackets instead of parentheses).

Also, a Function call without new, it's just a function call, so if you have this.someProperty = someParameter,
when you call the function, this.someProperty is undefined, while when calling with `new`, it's defined to the parameter value, because the new keyword makes that function call special, creates an unique object ouf ot it.

![image](https://github.com/DanielXMoore/Civet/assets/10191085/5495ab78-866e-46b9-972c-595f9fa5891d)

Also, an ESM class is an object with a constructor method, and using `new`, calls that constructor method, so the class it's not a function per se, and calling the constructor method manually doesn't do the same effect as with `new`.

Also, `new Foo` and `new Foo()` are equal because they are both called with the `new` operator, the only difference is that JS/TS allow the parentheses to be omitted if we aren't going to pass arguments to the constructor.

Also:

![image](https://github.com/DanielXMoore/Civet/assets/10191085/86a78d38-86eb-43b4-814e-5c8a40b261de)

So as you can see, `new` operator does a lot of magic behind the scene.

### Solution

You can do this instead:

```ts
x |> ($: string) => new MyClass($)
```

You are giving the pipe a function to work with, and you pass the piped argument(s) to the constructor.

My 2 cents. Hope this helps you.

**Comment by bbrk24** [comment]
Sure, I never meant to imply that `new` was the same as just calling it. Anyone who's tried `if (new Boolean(false))` would know that.

What I mean is a more pragmatic concern for writing code. I would rather write `appendText decoder.decode new Int8Array stderrBuffer` as `stderrBuffer |> new Int8Array |> decoder.decode |> appendText`. I think it's obvious to say that `new Int8Array(stderrBuffer)` is a more useful interpretation of that first part than `new Int8Array()(stderrBuffer)`, even if it's not exactly a function call.

**Comment by angelhdzmultimedia** [comment]
> Sure, I never meant to imply that `new` was the same as just calling it. Anyone who's tried `if (new Boolean(false))` would know that.
> 
> What I mean is a more pragmatic concern for writing code. I would rather write `appendText decoder.decode new Int8Array stderrBuffer` as `stderrBuffer |> new Int8Array |> decoder.decode |> appendText`. I think it's obvious to say that `new Int8Array(stderrBuffer)` is a more useful interpretation of that first part than `new Int8Array()(stderrBuffer)`, even if it's not exactly a function call.

Ohhh it's a feature request! I understood as "help wanted" my apologies 😅

Yeah it would be nice if Civet allowed piping class constructors ;) I'm with you on that.

**Comment by angelhdzmultimedia** [comment]
😂🎉😍🔥👏🤯 They added it so fast! So cool! Made my day.
