### ISSUE TITLE
Strings can't be used with indented pipes at start of file

### ISSUE THREAD

**Issue by bbrk24** [DanielXMoore/Civet#1061]
These three code samples work fine:
```civet
x
  |> console.log
```
```civet
5
  |> console.log
```
```civet

'x'
  |> console.log
```
(note the extra newline in that last one!)

But this causes a parse error:
```civet
'x'
  |> console.log
```

**Comment by edemaine** [comment]
Reading https://tc39.es/ecma262/#directive-prologue I think we're not really following spec here, and could reasonably fix this case... Of course, we can't fully parse and look at top-level statements for directives, because that would be too late. Maybe we can just forbid `.` or `|>` on the next line after a string directive, though.

**Comment by STRd6** [comment]
Yeah, a lookahead for `Pipe` or `AccessStart` should cover almost everything.
