### ISSUE TITLE
`if (and)` with indented condition list

### ISSUE THREAD

**Issue by bbrk24** [DanielXMoore/Civet#1090]
This gives a ParseError saying it expected a `::=` where I have `undefined`:
```civet
        return if (and)
            upper.test exactOrAny.toString()
            lower.test exactOrAny.toString()
        then exactOrAny
        else undefined
```
If I oblige and change the last line to `else ::= undefined`, the result is not remotely what I wanted out of this expression (and in fact not valid TS):
```ts
        return (((a,b) => a&&b)?(
            upper.test(exactOrAny.toString()),
            lower.test(exactOrAny.toString())):void 0)
        then(exactOrAny)
        type else = undefined
```
I was hoping to get this:
```ts
return (upper.test(exactOrAny.toString()) && lower.test(exactOrAny.toString())) ? exactOrAny : undefined;
```

**Comment by edemaine** [comment]
Currently we forbid indented function application in an `if` condition, to avoid confusion with the usual "then" block. For example:

```js
if foo
  bar
↓↓↓
if (foo) {
  bar
}
// NOT
if foo(
  bar
)
```

Perhaps we could make an exception when there's an explicit `then`. Meanwhile, you can wrap your condition in parentheses...

**Comment by bbrk24** [comment]
Just ran into this in a different context:
```coffee
return false unless (and)
  ...
```

**Comment by edemaine** [comment]
Ah, adding support for indented function application to *postfix* if/then should be easier to add. (...unless I'm missing some ambiguity...)

**Comment by edemaine** [comment]
I just attempted to implement postfix `if (and) [indented call]`, but failed.
I can see how to allow postfix conditions to use indented function application.
The problem is that there's *already* a parse for something like this:

```js
x = if (and)
  foo
---
x = ((a,b) => a&&b) ? foo : undefined
```

So in particular if we use `return` instead of `x =` this parse takes priority, preventing the postfix clause from activating.

---

Maybe we need to solve the root problem of how to use `(and) [indented call]` in a condition. I wonder if it would work (and be unambiguous) to allow an *indented condition* to use (further) indented function calls:

```js
// if/then/else
if
  (and)
    x
    y
  console.log 'yes'
else
  console.log 'no'

// postfix unless
return unless
  (and)
    x
    y
```
