### ISSUE TITLE
`&` doesn't always work in `if` statement

### ISSUE THREAD

**Issue by bbrk24** [DanielXMoore/Civet#1176]
For some reason, these generate invalid JS:
```civet
if & then x         // $ => if ($) x
return if & then x  // $ => return ($ ? x : void 0)
```
While these do not:
```civet
foo if & then x   // foo(($) => ($ ? x : void 0))
f := if & then x  // const f = ($) => ($ ? x : void 0)
```

**Comment by edemaine** [comment]
`return if & then x` is fixed via #1177.

The issue with `if & then x` is that it's an `if` **statement** instead of an **expression**. I guess in these situations we need to unbare the block (add braces) and call `insertReturn`. An example where this is actually useful:

```coffee
=>
  if & then y
```

[Playground link](https://civet.dev/playground?code=PT4KICBpZiAmIHRoZW4geQ%3D%3D)
