### ISSUE TITLE
Top-level string doesn't interpolate

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#118]
```coffee
"civet coffeeInterpolation"
"Hello #{name}!"
```

compiles to `"Hello #{name}!"` (incorrect)

```coffee
"civet coffeeInterpolation"
console.log "Hello #{name}!"
```

compiles to ``console.log(`Hello ${name}`)`` (correct)

**Comment by STRd6** [comment]
I think it has to do with caching. Since the "civet coffeeInterpolation" prologue directive changes the behavior of strings if it is followed by a string it may be parsed and cached. I'd prefer to not add strings to the non-cached list since that could affect parsing performance throughout the whole file.

Fine tuning the directive prologue parsing to only check for simple strings may fix this.

**Comment by edemaine** [comment]
Oh, I forgot about JS prologues. This behavior makes sense then, I think.

It might make sense to just clear the cache after parsing the Civet directive, though I'm not sure whether this is ever an issue.

**Comment by STRd6** [comment]
I probably need to add a comment in the parser since I forgot about it until reading the code :)
