### ISSUE TITLE
Implicit object literal calls vs class definitions

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#129]
@IamIpanda posted this example:

```coffee
class A
  a: number
  
class B extends A
  b: number
```

https://civet-web.vercel.app/#Y2xhc3MgQQogIGE6IG51bWJlcgogIApjbGFzcyBCIGV4dGVuZHMgQQogIGI6IG51bWJlcg==

Currently, this looks like and gets treated as a function call `A({b: number})`. But this is almost certainly not what the user meant. This is a special feature of classes where we can have bare type declarations like `b: number` (`FieldDefinition` within `ClassElementDefinition` within `ClassElement`).

@STRd6 What's the best way to communicate that `ExtendsClause` shouldn't, at the top level, use the implicit-function-call-with-implicit-object rule? Do we need to duplicate the whole rule tree from `LeftHandSideExpression`? Or set some state and disable caching? Pretty annoying...

It's not strictly necessary, but we ideally would still allow implicit function calls *not* at the top level, e.g.:

```coffee
class B extends (A
  b: c
)
```

Update: Oh, I notice `IndentedApplicationAllowed` is exactly for this purpose. Just need to figure out which cache rules to invalidate...

**Comment by STRd6** [comment]
@edemaine The same situation comes up in `if`, and `case`. For those I've used `ExpressionWithIndentedApplicationSuppressed` which seems to work pretty well. It could probably be improved since it doesn't push and pop state in the parser (the state could become inconsistent in certain backtracking situations) but works in common cases.

For `ExtendsTarget` we can probably use `ExpressionWithIndentedApplicationSuppressed` in place of `LeftHandSideExpression`. There may be further refinements necessary but this should be an improvement.

**Comment by STRd6** [comment]
Do we want to allow?

```
class C extends if x then A else B
  b: c
```

If so `ExpressionWithIndentedApplicationSuppressed` would be the one to use.
