### ISSUE TITLE
Generate normal `.d.ts` extension

### ISSUE THREAD

**Issue by danielbayley** [DanielXMoore/Civet#1316]
`civet --emit-declaration` always seems to produce e.g `index.civet.d.ts` files, but do we not ideally want to generate `index.d.ts` for release?

Otherwise, should it at least respect `--js` or `--output` to produce `index.d.ts`?

**Comment by edemaine** [comment]
The idea is to match the default extension for compiled output, `index.civet.[jt]sx`. I don't quite recall why that's the default but I think it's so that `index.civet` might resolve correctly with implicit extensions... 

If you specify an alternative extension via say `--output .ts` then I would have expected the dts to be `index.d.ts`. If that's not the case, I think it's a bug.

Not sure how `--js` would matter; you can't have `.d.js` files can you?

**Comment by danielbayley** [comment]
> The idea is to match the default extension for compiled output, `index.civet.[jt]sx`.

Cool, but then surely it should also change along with any specified change from that default.

> If you specify an alternative extension via say `--output .ts` then I would have expected the dts to be `index.d.ts`. If that's not the case, I think it's a bug.

Yeah, if I do `civet --compile index.civet --emit-declaration --output .ts`, it still produces `index.civet.d.ts`.

> Not sure how `--js` would matter; you can't have `.d.js` files can you?

Ha no, I just meant in that case we are most likely compiling the final `*.js` files, and so would want the corresponding generated type definition files correctly named as `*.d.ts`, rather than ending up with e.g `index.js` and `index.civet.d.ts`, right?
