### ISSUE TITLE
Allow control over the value that the `loop` expression "returns"

### ISSUE THREAD

**Issue by spenserblack** [DanielXMoore/Civet#1395]
I literally just stumbled on this language a few minutes ago, so I do apologize for raising this suggestion while being as inexperienced in the language as possible, and I certainly don't want to disrupt any behavior that the community already enjoys. I did want to raise this as a suggestion, because I've found this to be very enjoyable behavior in Rust.

Basically, in Rust, [`break` can be used to "return" a value from `loop`, and only `loop` (not `while` or `for`)](https://doc.rust-lang.org/std/keyword.break.html).

```rust
const FAVORITE_NUMBER: u8 = 7;

fn main() {
    let mut i = 0;
    let selected = loop {
        if i == FAVORITE_NUMBER {
            break i;
        }
        i += 1;
    };
    println!("{selected}"); // 7
}
```

Once I saw that Civet had the `loop` keyword, I looked to see if this same behavior was possible. I didn't see anything like it in the reference. I wanted to bring this up to ask if
- This is feasible to implement (it might conflict with `break LABEL`)
- This is desirable desirable to the Civet community

**Comment by edemaine** [comment]
Thanks for sharing your idea; I didn't know about that Rust feature. You're right that it in its literal form it conflicts with `break LABEL` (does Rust not have label-based breaking?), but something like it might be possible.

We had some related ideas here: https://github.com/DanielXMoore/Civet/discussions/1083 . In this world, we imagined supporting something like this:
```js
loop.value = x
break
```

So the above example could be written like so:
```js
FAVORITE_NUMBER := 7

function main
    i .= 0
    selected := loop
        if i == FAVORITE_NUMBER
            loop.value = i
            break
        i++
    console.log selected // 7
```

I think this is a bit clearer, in fact. But it does require two lines instead of one to "break with value", so it would be a bit annoying if we were trying to do something more concise like `break i if i == FAVOITE_NUMBER`.

We never got around to implementing this, and it's still open for discussion. We could also explore other syntaxes like `break with <value>`. The reason we went with this proposal was that, in general, it wasn't clear whether `break with <value>` should replace the entire return value, or append to the value so far, or what, and giving direct access to the return value seemed most powerful. I think even `loop` has that ambiguity, because currently you can [write this](https://civet.dev/playground?code=dmFsdWVzIDo9IGxvb3AKICBicmVhayBpZiBpID4gMTAwCiAgYXJyYXlbaSArPSBza2lwXQ%3D%3D):

```js
values := loop
  break if i > 100
  array[i += skip]
```

**Comment by STRd6** [comment]
Another possibility (might have been mentioned somewhere before but I couldn't find it with a quick search): `break with value`

```
function main
    i .= 0
    selected := loop
        if i == FAVORITE_NUMBER
            break with i
        i++
    console.log selected // 7
```

It could also be used with labels:

`break outer with []`

**Comment by edemaine** [comment]
Maybe both ideas are good; `break with` for overriding the return value entirely, and `loop.value` (and `for.value` etc.) for manually modifying e.g. pushing to the array.

Should we also consider `continue with`? I think that would naturally push a different value, though that maybe makes things inconsistent with `break with`. (I believe this is the rabbit hole discussion that led to the `loop.value` design. 🙂 )

**Comment by STRd6** [comment]
It seems like both syntaxes are largely compatible. `continue with` being `results.push` seems fine. There may also be situations where modifying the result value directly comes into play so `loop.value` may be useful as well. Probably just leave the details up to an actual PR to figure out the nitty gritty.

**Comment by spenserblack** [comment]
> does Rust not have label-based breaking

Regarding this, Rust uses labels that look a lot like lifetime parameters (`'label`). Not really applicable to this issue, but if you're curious, [this is what it looks like](https://doc.rust-lang.org/rust-by-example/flow_control/loop/nested.html).

IMO `break with` is pretty clear. And I think it's helpful that it's using two existing JS keywords in a new way.

IDK if this is valid, but I had the idea of calling `break` like a function to "pass" a value. `break(value)`.

**Comment by edemaine** [comment]
Thanks! In Civet, though, `foo(value)` and `foo value` are equivalent, so I don't think we want to define `break(value)` in a way differs from `break value`.

**Comment by spenserblack** [comment]
Good point. Also, I can see how it can be confusing if a keyword *looks* like a function, but it's actually not.

I assume that `loop.value` would also be an accessor/getter, not just a setter? Funnily enough, this reminds me of Django's template language, which includes things like `forloop.counter`. Which *then* reminds me that they have `forloop.parentloop` to access the outer loop. So if you use the `loop.value` style, I assume you'd need something similar if you want to modify the outer loop's value from an inner loop? Personally I feel like `loop.value` is a bit confusing since it looks like `loop` is a global value when it's actually not.

IMO `break with` and `continue with` is ideal, especially since I (optimistically) believe it can be cleanly combined with labels, like `break :label with value` or `break with value :label`, which can help identify which loop's value you're working with (side-note: I love that labels can be written in that Ruby symbol-like way).

But, regarding `loop.value`, `for.value`, and I'm assuming `while.value`, I'm reminded that Go simplified all of their loops to only the `for` keyword.
- `for {}` == `loop {}`
- `for expr {}` == `while (expr) {}`
- And of course, the other, more well-known types of `for` loops

Now this proposal by itself certainly shouldn't disrupt Civet in such a way -- it's simply not important enough IMO. But I couldn't help but think that having one universal `for.value` would be much easier to learn/implement than something for each type of loop.

**Comment by edemaine** [comment]
We now have `break with ...` and `continue with ...`! See [docs](https://civet.dev/reference#controlling-loop-value). These were easier to implement than `loop.value`/`for.value` anyway (though I think they also point the way to how to implement those), so it was fun to do.  Catches:
* Not yet released. (Let me know if you want to play with it now.)
* `break label with ...` is still to-do.


> So if you use the `loop.value` style, I assume you'd need something similar if you want to modify the outer loop's value from an inner loop?

One nice thing about `loop.value` and `for.value` being distinct is I think it's rarer to nest same-type loops. If you had a `for` inside a  `loop`, `for.value` and `loop.value` would refer to different things. But for the general case we were thinking `for:label.value` or maybe `:label.value`.

> Personally I feel like `loop.value` is a bit confusing since it looks like `loop` is a global value when it's actually not.

It's modeled after other keyword property syntaxes: `await.all`, `import.meta`, etc. Admittedly these behave more like globals than `for.value`... Generally keyword properties are nice because they weren't possible before so it remains backward compatible.

Alternatively, we could forget about `for.value` and just allow `:label.value`, thereby requiring a loop to be labeled if you want to read or modify its value in a general way. Maybe that's clearer?

**Comment by spenserblack** [comment]
Wow, that was really fast turnaround! :tada:

> It's modeled after other keyword property syntaxes: `await.all`, `import.meta`, etc. Admittedly these behave more like globals than `for.value`... Generally keyword properties are nice because they weren't possible before so it remains backward compatible.

That's my bad, I should have learned this language in more detail before offering my opinion on that. If keyword properties are already a precedent, then it sounds like `loop.value` is a good idea.

I'm not sure how big of a deal it is, but I just wanted to raise for consideration that, even if it's unlikely, it is possible to have two or more nested `loop`s, making `loop.value` ambiguous. If you feel that's too theoretical and doesn't reflect actual usage, that's totally valid IMO! I personally can't think of any real-world usage that would require nested `loop`s and `loop.value` -- at least not something that can't be handled with the new `break with`.

**Comment by edemaine** [comment]
Oh yes, nested same-type loops definitely exist! `for` is especially common. The idea with `for.value` was to address the common case, and then you'd use labels (and `for:label.value` or maybe `:label.value`) to disambiguate the ambiguous cases.

**Comment by spenserblack** [comment]
:laughing: I got so focused on the `loop` loop that I forgot about the type of loop that everyone uses 99% of the time :sweat_smile:

I'm thinking that the label can be optional, just like how a label is optional for `break` and `continue`. If it's omitted, it references the current loop, if it's included, it references the labelled loop.
