### ISSUE TITLE
Pattern Catching

### ISSUE THREAD

**Issue by bbrk24** [DanielXMoore/Civet#1473]
Been discussed on the Discord before but I didn't see an issue

Prior art includes Swift [`catch`](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/guidedtour#Error-Handling) and C# [`catch`-`when`](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/when#when-in-a-catch-clause)

**Comment by edemaine** [comment]
It would be nice to flesh out a specific syntax proposal and/or specific features you want. Here are a few possibilities:

## 1. `catch switch`

@STRd6 has suggested the following in the past I believe:

```js
try
  //...
catch switch
  <? RangeError
    // like a normal pattern-matching switch
```

One thing that's not clear with this syntax is how to get the error object. Should `catch switch e` bind `e` to the error? It's a little funny-looking (`e` is a left-hand side here, whereas usually the argument to `switch` is a right-hand side), but it could work.

Actually, the following form [already works](https://civet.dev/playground?code=dHJ5CiAgLy8uLi4KY2F0Y2ggZSBzd2l0Y2ggZQogIDw%2FIFJhbmdlRXJyb3IKICAgIC8vIGxpa2UgYSBub3JtYWwgc3dpdGNoCg%3D%3D)!

```js
try
  //...
catch e switch e
  <? RangeError, <? ReferenceError
    //...
  {message: /bad/}
    //...
  else
    // other exception
```

So a very simple thing would be to drop the requirement of `e` here, and then we get all the power of pattern matching (including future features).

## `catch <pattern>`

It would also be nice to avoid the word `switch`. Part of the problem here is that pattern-matching `switch` doesn't have a word before the cases, like `case` or `when`, so it's hard to infer the `switch`. But here's one possible syntax that might be good: put the pattern (instead of an identifier) right after `catch`.

```js
try
  //...
catch <? RangeError, <? ReferenceError
  //...
catch {message: /bad/}
  //...
catch e
  // other exception
```

Multiple `catch` blocks seems to be the way of Swift, C#, and Python, so this seems reasonable.

## `catch...when`

Alternatively, if we just wanted a limited form of pattern catching that supports, say, types only (like [Python's `try...except`](https://docs.python.org/3/tutorial/errors.html#handling-exceptions)), we could do something like `switch...when`:

```js
try
  //...
catch e
  when RangeError, ReferenceError
    //...
  when TypeError
    //...
  else
    // other exception
```

Plausibly we could do multiple of the above proposals, for different situations. I believe they are all mutually compatible. But it'd be nice to see some real examples to better judge.

**Comment by bbrk24** [comment]
>  But it'd be nice to see some real examples to better judge.

Most of my real-world examples are type checking ([example 1](https://github.com/bbrk24/Trilangle/blob/d0de96201902864c5182f6e60d7e36a7d7bc0629/wasm/worker.civet#L67), [example 2](https://github.com/bbrk24/template-qdeql/blob/fe7e153a72b01539e81be6cc3ac72206f950047b/src/compiler.civet#L66), [example 3](https://github.com/bbrk24/template-qdeql/blob/fe7e153a72b01539e81be6cc3ac72206f950047b/src/index.civet#L99)). However, there are cases where I want to check other information about an error than just its type: [example from a Civet project](https://github.com/bbrk24/template-qdeql/blob/fe7e153a72b01539e81be6cc3ac72206f950047b/src/qdeql.civet#L46), [example from a TS project](https://github.com/xsduan/conniebot/blob/a0da0833cda37dda65ffffc4089e8ab10bd47932/src/conniebot.ts#L271). In both of these cases I still do a type check -- the former requires it so that TS is okay with me accessing the `.message` property, while the latter is semantically required -- but I also check something about the properties.
