### ISSUE TITLE
Strange behavior when using arrow function with @ parameter

### ISSUE THREAD

**Issue by lukegustafson** [DanielXMoore/Civet#1489]
I'm not sure if this is even a documented feature, but I somehow noticed this. Here, the `1` is unexpectedly getting separated from the arrow function:
```
(@a)=>1
//becomes
(a) => (this.a = a);
1;
```
Interestingly, it works fine with `->` instead of `=>`.

If it's not supported syntax, it would be nice to get an error at compile time instead of incorrect code.

**Comment by bbrk24** [comment]
I'm surprised that compiles at all. I wasn't aware `@a` worked outside of constructors, let alone in arrow functions that don't even have a `this` value.

Given my past experience with arrow functions breaking, it's unsurprising to me that, given your compilation, this works as expected:
```
(@a) =>
  1
```
Moving the `1` to the next line makes Civet consider it a statement rather than an expression, and it wraps the function body in braces, leading to this compilation:
```js
(a) => {
  this.a = a;
  return 1;
}
```

**Comment by edemaine** [comment]
Thanks for the report! My guess is that we're forgetting to brace the block when adding this assignments.

@bbrk24 Yeah, we allow destructuring of `@x` pretty much everywhere. In this case, it would be setting the outer `this`.
