### ISSUE TITLE
Weird Operator Behavior

### ISSUE THREAD

**Issue by STRd6** [DanielXMoore/Civet#511]
```
operator min

min 1, 2
min 1, 2
```

Becomes:

```
min(1, min(2, 1), 2);
```

It should be:

```
min(1, 2)
min(1, 2)
```

Adding semi-colons or assignments fixes it.

https://civet.dev/playground?code=b3BlcmF0b3IgbWluCgptaW4gMSwgMgptaW4gMSwgMg%3D%3D

**Comment by edemaine** [comment]
Fair point; that definitely seems confusing.

We currently allow binary operators at starts of lines to continue lines. For example:
```coffee
x := 5
- x
or y
---
const x = 5 - x || y
```

I think this makes sense for symbol operators, and probably other built-in operators like `and` and `or`, because it couldn't mean anything else (in particular because `- x` currently cannot be interpreted as a unary `-`). For comparison, this isn't supported in CoffeeScript but part of it was proposed in https://github.com/jashkenas/coffeescript/pull/5279

Perhaps custom operators should allow this only when they are `IndentedFurther`. So if you intended the current compilation of your example, you could write it this way:
```coffee
min 1, 2
  min 1, 2
```

**Comment by STRd6** [comment]
I don't think it makes sense for our current custom operators since they are not infix, but it could make sense if they were.

**Comment by edemaine** [comment]
What do you mean that they're not infix? `operator` is specifically for making infix operators. Do you mean that they're optionally infix?

**Comment by STRd6** [comment]
You're correct, I had a moment of confusion.

The optionally infix is what I think this makes this behavior weird. I can see allowing your example of using `IndentedFurther` to match a custom operator as infix but it probably shouldn't match as infix if on the next line at the same level of indentation.

```coffee
min 1, 2
  min 1, 2
```

Has this as a sensible parse:
```typescript
min(1, (2
  min 1), 2)
```

```coffee
min 1, 2
min 1, 2
```

Should parse like this:

```typescript
min(1, 2)
min(1, 2)
```
