### ISSUE TITLE
add autoConst

### ISSUE THREAD

**Issue by SBHattarj** [DanielXMoore/Civet#527]
Just a feature request as by default I like to use const if I don't need to mutate some variable. So having autoConst would be usefull.

**Comment by STRd6** [comment]
Can you provide a more detailed example of how it would work? Would it raise an error if a variable is reassigned or default to `let` in that case? If it does default to `let` would the exisitng `autoLet` be fine? I'm trying to understand when and how this feature would be used.

Thanks!

**Comment by edemaine** [comment]
I'm just guessing here, but my initial read was this:

```js
"civet autoConst"
x = 5
y .= 10
var z = 0
↓↓↓
const x = 5
let y = 10
var z = 0
```

Essentially like `autoLet`, but all automatic variable declaration is via `const` instead of `let`, and you can override via explicit declaration (`let`, `var`, or `.=` shorthand). The following would either fail to transpile or generate the invalid JS:

```js
"civet autoConst"
x = 5
x = 10
↓↓↓
const x = 5
const x = 10
```

But this is just a guess. @SBHattarj Is this what you had in mind, or something else?

**Comment by GoToLoop** [comment]
I wish there was a shorthand for `var` as well. 😿

**Comment by STRd6** [comment]
> I wish there was a shorthand for `var` as well. 😿

Feel free to open a discussion! I'd be happy to add it if we can find a good syntax for it.

**Comment by SBHattarj** [comment]
> 

That is precisely what I meant. I do not personally understand parsing, otherwise I would have sent a PR
