### ISSUE TITLE
Babel plugin / Using Civet with metro bundler in react native

### ISSUE THREAD

**Issue by bennidi** [DanielXMoore/Civet#536]
It is itching under my finger nails to try out civet in one of my personal projects to build a react native mobile application.
Is there a plugin available for the metro bundler? What would be the recommended way of integration?
Does anybody have experience with Civet and react native stack?

**Comment by edemaine** [comment]
@bennidi Can you try the new Babel plugin to see how it works for you?

https://github.com/DanielXMoore/Civet/blob/main/source/babel-plugin.mjs

**Comment by bennidi** [comment]
Thank you so much for that work. I am currently on a two month vacation. I
can not promise anything but I definitely keep it in mind for the next
programing sessions.

**Comment by etherealHero** [comment]
I'm trying to use civet in react native and I get the following error:

![babel-need-cjs](https://github.com/user-attachments/assets/24de0433-233d-4e4f-9756-5cf2f55906c1)

I tried to solve the problem of setting up babel config for react native to make it work, but I couldn't find anything. 

Then I tried modifying civet's source a bit so that it also created the commonjs babel plugin, and it worked fine.

Here's what you need to do in your react native project to support .civet (if civet will also create babel in commonjs):

```diff
// install civet in react native project
yarn add -D @danielx/civet

// include .civet files to module resolution in metro.config.js
-const config = {};
+const config = {
+  resolver: {
+    sourceExts: ['js', 'jsx', 'json', 'ts', 'tsx', 'civet'],
+  },
+};

// add plugin in babel.config.js
 module.exports = {
   presets: ['module:@react-native/babel-preset'],
+  plugins: [['@danielx/civet/babel-plugin']],
+  sourceMaps: 'inline',
 };
```

I'll try to post a PR with babel commonjs added. I can also make a repository with an example react native project using civet to add a link to the civet site if required (Just like others have done with Solid templates)

**Comment by bennidi** [comment]
@etherealHero This is amazing. Thank your for picking up on this and finding a solution. I hope the PR gets merged soon.

Side question: Will you use Civet full on or just for specific parts? Do you have experience using civet in other react projects?

**Comment by etherealHero** [comment]
In general, in react native, sources can be written using all .js .tsx .civet extensions together, within one project. metro bundler handles all this perfectly. I also tried writing everything in .civet (and the entry point index.js > index.civet too) and that also works well. my goal is to get acquainted and learn react native. And I recently found out about civet and really liked it. Therefore, I decided to combine these things, and I think that the entire project on react native will be on civet. (in addition, we disable ts lsp and use only civet lsp - it will be more convenient). There are no ready-made react projects with civet yet. That's how I think, if I understand the essence of the question

**Comment by bennidi** [comment]
Thank you Maxim for your informative response. I wish you all the best for your venture into react native.
I will probably try to mix some civet files into my stack as well.
Just that I am also aware that apart from its many useful shorthands, it is also unwieldily unreadable in some occasions.
I wish it would hit more of a sweet spot and provide only some of the suggested improvements like everything is an expression and the pattern matching but stay away from weird implicit assignment in conditional and other more obscure concepts.

Back in the days I used to love coffeescript and really got into it. However, every colleague of mine could not handle my codebases easily because of the exotic syntax. There is actually a lot of hidden complexity in the semantics of civet (you need a lot of mental conversion steps to understand in which way code is executed).

So, welll.....My excitement stopped a bit.

**Comment by edemaine** [comment]
@etherealHero Thanks for your improvements! Do you think it's worth adding an example (for React or React Native) to https://github.com/DanielXMoore/Civet/tree/main/integration/unplugin-examples ?

**Comment by etherealHero** [comment]
In fact, there is a question of two lines of code in the react native configs. And this example is a special case of babel with additional metro bundler config settings. I think making a full-fledged template just like with solid would be redundant. I think it would be a normal solution to add something like this to the integration page:

...
## Starter Templates
[Astro, esbuild, NextJS, Rollup, Vite, and Webpack](https://github.com/DanielXMoore/Civet/blob/main/integration/unplugin-examples)
[Solid](https://github.com/orenelbaum/solid-civet-template)
[SolidStart](https://github.com/orenelbaum/solid-start-civet-template)
## React native
To integrate into react native, you need to tell metro bundler to [allow the civet extension](https://metrobundler.dev/docs/configuration/#sourceexts) and add the [babel plugin](https://github.com/DanielXMoore/Civet/blob/main/source/babel-plugin.civet) to the corresponding config like this:
```diff
// include .civet files to module resolution in metro.config.js
-const config = {};
+const config = {
+  resolver: {
+    sourceExts: ['js', 'jsx', 'json', 'ts', 'tsx', 'civet'],
+  },
+};

// add plugin in babel.config.js
 module.exports = {
   presets: ['module:@react-native/babel-preset'],
+  plugins: [['@danielx/civet/babel-plugin']],
+  sourceMaps: 'inline',
 };
```
## Linters
[eslint plugin](https://github.com/DanielXMoore/Civet/blob/main/integration/eslint)
...

I can do this in the first half of the work week if this decision is agreed upon. I also noticed that the link to the babel plugin on civet.dev **was broken** since it referred to source/babel-plugin.mjs, and now it is source/babel-plugin.civet  (I didn’t keep track of this when I did the PR)
