### ISSUE TITLE
An empty object in if statement

### ISSUE THREAD

**Issue by imm** [DanielXMoore/Civet#559]
Hi,

An empty object inside a conditional statement breaks everything:
```coffee
if condition
  {}
```
compiles to
```js
if (condition)
  {
```
I needed this in a function to return an empty object on some condition, so
```coffee
f = -> 
  if condition
    {}
```
compiles to
```js
f = function() { 
  if (condition)
    {;return
}
```

[Playground](https://civet.dev/playground/?code=aWYgY29uZGl0aW9uCiAge30KCmYgPSAtPiAKICBpZiBjb25kaXRpb24KICAgIHt9)

**Comment by STRd6** [comment]
Thanks for the report! This is definitely a bug and something we'd like to fix soon.

**Comment by edemaine** [comment]
I looked at the grammar some to see why this happens.  Here are some relevant rule excerpts to save some time:

```hera
IfStatement
  (IfClause / UnlessClause) Block ElseClause?
IfClause
  If Condition:condition
ElseClause
  Samedent Else Block
  _? Else Block
Condition
  ParenthesizedExpression !( _? ( BinaryOp / AssignmentOp / Dot / QuestionMark ) ) !( _ OperatorAssignmentOp )
  InsertOpenParen ExpressionWithIndentedApplicationForbidden:expression InsertCloseParen
  # and more for DeclarationCondition
# NOTE: This is the body of if/else/for/case etc.
Block
  ExplicitBlock
  ImplicitNestedBlock
  ThenClause
  _?:ws !EOS Statement:s
ExplicitBlock
  __ OpenBrace NestedBlockStatements? __ CloseBrace ->
```

So `ExplicitBlock` wins in particular because it doesn't care about spacing.

I guess the first question is what behavior we want.  For example, do we want `if (cond) {}` to behave like it does in JavaScript?  What about the following (valid JS)?

```js
if (cond)
{}
```

One possible rule is: if the condition has parentheses (JS-style), then following braces are treated like a block, like they are currently.  And we could require indentation for the implicit parens model.

Another possible rule is: try to parse as a nested block first, so it takes priority over `ExplicitBlock`.  This rule would make the previous example work, because the `{}` isn't indented. It should also work for `{` on the same line as the `if`, because again it isn't indented:

```js
if (cond) {
}
```

I guess the weird case is the following:
```js
if (cond)
  {}
```
Should this be treated the same as the original example with `if cond`?  Or should we treat it as an object literal given the indentation?  I'm hoping the latter is "sufficient" JS compatibility, in particular because it'd be easier to implement. It's literally just swapping the order of `ExplicitBlock` and `ImplicitNestedBlock`.  I'll make a PR.
