### ISSUE TITLE
`do` expressions without `while`/`until`

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#58]
Oren wanted something like this on Discord: (originally suggested without `do` keyword)

```coffee
x = do
  y := 5
  y + 1
```

It does seem like a natural extension to `do ... while` currently supported, i.e., make the `while` optional. It also corresponds to [this proposal](https://github.com/tc39/proposal-do-expressions) (though we don't need that proposal for `if`/`while` expressions).

Related, I expected this to work, but it doesn't parse: (it works without the `:=`)

```coffee
x = if true
  y := 5
  y + 1
```

Current workarounds, which work but are a bit inefficient as they create arrays:

```coffee
x = (do
  y := 5
  y + 1
while false)[0]
```

```coffee
x = (for nothing of [1]
  y := 5
  y + 1
)[0]
```

**Comment by STRd6** [comment]
```
x = if true
  y := 5
  y + 1
```

That doesn't parse because the `if` is in an expression position and you can't have declarations inside expressions. A possible solution would be to auto-iife wrap expressions with declarations in them (CoffeeScript does that). Another posibility would be to distribute the assignment into the if branches and keep everything at statement level.

**Comment by edemaine** [comment]
> A possible solution would be to auto-iife wrap expressions with declarations in them (CoffeeScript does that).

I would lean this way; the current behavior feels asymmetric with `for` and `do` loops. Admittedly it's a bit of an edge case but I like consistency.

**Comment by lorefnon** [comment]
Besides being inconsistent, the if expression restriction is also non intuitive to people coming from languages like kotlin where despite being expressions if can have body with multiple statements. 

Maybe I haven't thought through the edge cases completely, but could we instead use a temporary variable ? 

```ts
let tmp$1

if (true) {
  const y = 5
  temp$1 = y + 1
}

x = tmp$1
``` 

That way we won't have an additional function allocation+call+dispose overhead, stack traces will not have additional entry etc. 

Primary problem I see is that it compromises the type checking. 

One way to solve that is we create a function for ts to infer the return type, but don't actually use it. In js mode the function can be skipped completely, or a dead code eliminator will take care to remove. 

 
```ts
function unused__infer$1() {
  const y = 5
  return y + 1
}

let tmp$2: ReturnType<typeof unused__infer$1>

if (true) {
  const y = 5
  temp$2 = y + 1
}

x = tmp$2
``` 

The output becomes uglier now though.

**Comment by STRd6** [comment]
@lorefnon I think the temp variable with the TypeScript inference is a good goal for all expressionized statements (if/do/while, etc.)

As for the alternative `=>` I disagree about using the function arrow since the function just happens to be an implementation detail and will ideally be removed once the compiler becomes smarter.

**Comment by STRd6** [comment]
It looks like TypeScript can infer correctly with plain blocks: https://www.typescriptlang.org/play?#code/DYUwLgBGC2AOAkBGAUMg3siEDGB7AdgM6QCeEAvBAKyZRxIURkDUEKAvqnkZAB6MwEKIA

Also type inference works with `do { ... } while(false)` blocks. I think the key is that the variable is assigned the same type on all paths.
