### ISSUE TITLE
Postfix `if` doesn't add destructure declaration to block

### ISSUE THREAD

**Issue by STRd6** [DanielXMoore/Civet#702]
```civet
x if { x } := y
```

Expected

```
let ref;
if ((ref = y)) {
  const { x } = y;
  x;
}
```

Actual
```
let ref;
if ((ref = y)) {
  x;
}
```

**Comment by gwhitney** [comment]
Wow, I learned from this that JavaScript chose the value of the destructuring assignment `({x} = y)` to be `y`, not `{x}`. Seems like a very strange choice because it means that `({x} = {y} = z)` does not mean the same thing as `({y}=z); ({x}={y});` which seems very counterintuitive. But oh well, I guess the TC39 knows best ;-).
