### ISSUE TITLE
Parse errors around division and space

### ISSUE THREAD

**Issue by unlessgames** [DanielXMoore/Civet#822]
Seems like if you write a division with a space before the slash but none after it leads to a parse error as the parser thinks it's the start of a regular expression I guess.

* `2 / 3` is ok
* `2/3` is ok

```
2 /3
``` 
parseError at the end of the line regardless of where this occurs which is even more misleading if the expression hides in the middle.

Somewhat related to #221

**Comment by bbrk24** [comment]
I've asked about this on the Discord before, and the fact that inconsistent spacing isn't allowed is apparently intentional. Swift has the same rule, for what it's worth.

**Comment by unlessgames** [comment]
That's an understandable rule but then I think it would be nice to make it clear on the website and to have the rule be enforced consistently. 

Currently `2/ 3` is ok while `2 /3` is not, tested the same in Swift online and both of these throw an error there.

Furthermore, the Swift is clear about what and where the issue is.

```swift
let x = 1.0 /2.0 + 3.0 * 4.0 / 5.0
//          ^ it will show the error here saying 
//               "'/' is not a prefix unary operator"
```

Trying to do the same thing in civet even transpiles! :o
```coffee
let x = 1.0 /2.0 + 3.0 * 4.0 / 5.0
```
into this (which throws a TypeError when running)
```js
let x = 1.0(/2.0 + 3.0 * 4.0 /(5.0));
```

Adding parens will make it into a parse error but it will happen on the next unrelated non-comment line.

```swift
let x = (1.0 /2.0) + 3.0 * 4.0 / 5.0
// imagine some comments

// that can take you even further
// from the source of the error
let z = 6.0
// ^ parseError will point to here without any hint on consistent spacing
```

**Comment by edemaine** [comment]
I wrote https://civet.dev/comparison#operator-spacing to document this behavior. Let me know if you have ideas for further improvement! (in a PR or a comment here)

Currently, spaces are allowed after but not before a binary operator, and I've documented that. This makes a lot of sense for the `,` operator in particular; not sure it makes particular sense for others, but I'm not sure it's necessary to forbid them?  We need the rules we have, and not more, because of ambiguities with implicit function calls.

Good error messages are a bit of an open problem...

**Comment by unlessgames** [comment]
Thank you! That's looks great.

Only improvement that comes to mind would be adding some code example(s) for the spacing that *would* lead to a parse error to make it more clear what to avoid in the future.

About the rules themselves I am still a bit confused. The explanation says 

>Currently we also allow space after but not before the operator, which is common e.g. with the , operator.

But in practice the `,` operator seems to have special behaviour regarding this.
* `Math.min 2 ,3` is ok
* `Math.floor 2 /3` is not

I obviously can't see all the implications of rule enforcement here but as a user it would be more clear to me if inconsistent spacing would be a hard no for all, except the `,` operator which would only allow for `no-space,space` in addition to consistent spacing. Right now it seems it is already treated differently but in the opposite way I'd expect.

**Comment by edemaine** [comment]
Good ideas! I've added some invalid examples to help clarify. (But they have to be commented out to prevent the documentation from crashing. 😅 )

I've removed the mention of the comma operator, because that was confusing. In fact, we treat `,` completely differently, not as a binary operator. So it's better not to mention it; anything is allowed when it comes to commas. (Also, `Math.min 2, 3` does not use the comma operator. I meant more `2, 3`.)

Hopefully the "Currently" sentence is now clear: we allow `x+ y` but we might not in the future, opting for the more consistent behavior you propose.

**Comment by 747** [comment]
@edemaine Thank you for the documentation, but it looks like:
![image](https://github.com/DanielXMoore/Civet/assets/3427854/d6d6bc61-421d-4cb9-8bfa-bef4cd795250)
Is it intentional that JSX eats the comment-like expression?

**Comment by edemaine** [comment]
Oops. Yes, that's how JSX works, but it's not helpful as an example. I'll move the comment (or switch to an XML comment).

**Comment by edemaine** [comment]
Fixed. I think this issue is done? If not, let me know.
