### ISSUE TITLE
Specifics of unbraced literal syntax w/r/t commas and whitespace?

### ISSUE THREAD

**Issue by gwhitney** [DanielXMoore/Civet#995]
Are the exact rules of unbraced literal syntax written down anywhere in human-readable/narrative form (i.e. if I am not strong enough in the Force to (want to) read the Source)? I ask because for example

```
obj := a: 1, b: 2,
   c: 3, d: 4
```
produces the expected `{a: 1, b: 2, c: 3, d: 4}` but the pretty similar and arguably more uniform-looking
```
obj :=
   a: 1, b: 2,
   c: 3, d: 4
```
parses as the plain object `{a: 1}` applied to `{b: 2, c: 3, d: 4}`  which both throws an error and me for a loop ;-). I can't quite understand why Civet decides to close the first unbraced literal after the first comma and then interpret the space following that as function application. Maybe it has something to do with commas being optional when a key-value pair is on a line by itself? Anyhow, I guess when the clearest organization for my object uses multiple key-value pairs on each line I will just make sure to have at least one pair on the same line as the `:=` -- then it all seems to work as I'd hoped/expected.

**Comment by edemaine** [comment]
I think this was a bug introduced recently during a bit of an overhaul of implicit object literals (#976). Thanks for finding the bug! It turns out one of the (now three) types of object literals was not allowing for multiple properties on the same line. Hence the bad parse. Will be fixed shortly!

We don't have a spec written down for this. It's supposed to be somewhat intuitive, but there are some "rules" like "if ending a prop with a comma, can continue on next line in more cases" that could be interesting to try to write down. Probably the best document we have now is the [set of tests](https://github.com/DanielXMoore/Civet/blob/main/test/object.civet) which gives lots of examples of what's valid (and a few of what's invalid). We'll be adding your examples above to this list. 🙂
